### ISSUE TITLE
Kraken API v5 and v3 phasing out

### ISSUE THREAD

**Issue by mattnotmitt** [manumiranda/twitch-api#3]
https://blog.twitch.tv/action-required-twitch-api-version-update-f3a21e6c3410#.bemhbakzx
This is going to be interesting...

**Comment by manumiranda** [comment]
It is, for sure... haha 
So it's time to develop a new version that supports the v5 Twitch API =) TypeScript anyone?

(thanks for the note, @artemisbot )

**Comment by mattnotmitt** [comment]
I mean at least we've got until 2018, there won't even be docs for another month - everyone's gonna be having fun dealing with converting databases to IDs though (especially as it's only on v3 for some reason).

**Comment by manumiranda** [comment]
Once the docs are out, and as soon as I can, I'll start adapting the library for the new version.... wich will problably mean a rewrite from scratch... And that name to ID thing is going to have some implications form my apps too...

**Comment by natterstefan** [comment]
@manumiranda Hello, any news so far?

**Comment by manumiranda** [comment]
@natterstefan When I was trying to decide what to do with the new version (new version of the package? whole new development?) I found a library that specifically targets v5 of the twitch API - https://www.npmjs.com/package/twitch-api-v5
As far as I have seen, it covers the whole funcionality of the API and it seems well documented also, so I have been thinking about if its worth it to develop a new version or if it's better to add a notice on the frontal readme an center all efforts on that new package...

**Comment by roncli** [comment]
FYI v5 is now ALSO getting phased out, with both v3 and v5 ending support at the end of 2018.
